version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@1.0.1

jobs:
  install-and-test:
    executor:
      name: node/default
      tag: '16.17'
    steps: 
      - checkout 
      - node/install-packages
      - run:
          command: npm run test
          name: Run YARN tests
  
  build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - run: ./build.sh
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: <fingerprint>

workflows:
  Build and Deploy:
    jobs:
      - build_deploy
